### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by Fannasankh** [Featuretools/featuretools#313]
module 'tornado.platform.asyncio' has no attribute 'AnyThreadEventLoopPolicy'

-----
*Issues created here on Github are for bugs or feature requests. For usage questions and questions about errors, please ask on Stack Overflow with the [featuretools](https://stackoverflow.com/questions/tagged/featuretools) tag. Check the [documentation](https://docs.featuretools.com/#get-help) for further guidance on where to ask your question.*

**Comment by kmax12** [comment]
@Fannasankh can you share a reproducible example and details on your environment?

**Comment by Fannasankh** [comment]
I use Google Colab
example https://colab.research.google.com/drive/1pmXx4pEn4yw_pI5SU_wd20vPlVQl4Dvx

**Comment by Fannasankh** [comment]
> @Fannasankh can you share a reproducible example and details on your environment?
I use Google Colab
example https://colab.research.google.com/drive/1pmXx4pEn4yw_pI5SU_wd20vPlVQl4Dvx

**Comment by Fannasankh** [comment]
> @Fannasankh can you share a reproducible example and details on your environment?

I use Google Colab
example https://colab.research.google.com/drive/1pmXx4pEn4yw_pI5SU_wd20vPlVQl4Dvx

**Comment by stobasa** [comment]
Am having the same error. I use Anaconda environment on Ubuntu.

**Comment by rwedge** [comment]
Someone posted about this on stack overflow: https://stackoverflow.com/questions/53237312/import-featuretools-and-attributeerror-module-tornado-platform-asyncio-has-no

If I install a version of tornado lower than 5 I get this error when I try to import featuretools

**Comment by Fannasankh** [comment]
I tried version 5.1, but it did not help on Google Colab

**Comment by kmax12** [comment]
@Fannasankh this looks like an issue with the Google Colab environment supporting tornado 5.1. Looks like after you upgrade there is problem simply importing Tornado. 

@rwedge put up a PR to distributed (https://github.com/dask/distributed/issues/2351), which is the library we depend on, to fix the source of this issue. 

Is it an option to run the code locally or in a different environment for the time being?

**Comment by Fannasankh** [comment]
It works on version 4.5 and 5.1 locally, but updating a version of a tornado on google colab does not help

**Comment by Fannasankh** [comment]
And when i updating tornado on Google Colab to version 5.0/5.1 i have error "ImportError: cannot import name 'future_set_exc_info'"

**Comment by Fannasankh** [comment]
I fix this problem on Google Colab

!pip install distributed==1.23.3
!pip install dask==0.19.4
!pip install tornado==4.5.1

**Comment by kmax12** [comment]
Thanks for the digging into this and sharing the solution.
